version: '3.8'

services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gestao_vendas_app
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - jaeger
    command: [ "-c", "/app/wait-for-mysql.sh mysql:3306 && java -jar /app/gestao_vendas.jar"]
    entrypoint: [ "/bin/sh" ]

  mysql:
    image: mysql:5.7
    container_name: mysql    
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db

  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411